application/widgets/bookmarks_menu.py
Now user can mark letter of a bookmark with underscore to access it instantly via keyboard.
=> Enable mnemonics in bookmark list

application/plugins/file_list/file_list.py
Queue flushing in _add_item slowdown direcory loading. Anyway we flush queue just after _add_item call. So queue flushing in _add_item is unnecesary.
=> File list: Remove queue flushing from _add_item method. Fix MeanEYE/Sunflower#36

application/plugins/archive_support/zip_provider.py
This fixes zip_provider's handling odd ZIP files where files come before the directory that contains them (e.g. below unzip -t test.zip)
testing: test/                    OK
testing: test/.config/bar.txt     OK <-- comes before test/.config/
testing: test/.config/foo.txt     OK <-- comes before test/.config/
testing: test/.config/            OK
testing: test/bar/                OK
testing: test/foo/                OK
testing: test/foo/bar2.txt        OK
testing: test/foo/bar1.txt        OK
testing: test/foo/bar10.txt       OK
testing: test/.empty              OK
=> Fix zip_provider handling odd ZIP files

application/operation.py, application/plugin_base/provider.py, application/plugins/archive_support/zip_provider.py, application/plugins/file_list/gio_provider.py, application/plugins/file_list/local_provider.py
Fixes #95 
Use Gio::File::move instead of set_display_name when moving a file.
=> Changed MoveOperation to use Gio::File::move

application/plugins/archive_support/zip_provider.py
=> Zip provider: Renamed `_real_path` to `real_path`.

Makefile
Target `dist-deb` was failing with untar error:
```
tar: .//build/sunflower-0.3-60.tar: Cannot open: No such file or directory
```
This error was caused by going into `$(build_directory)` and trying to untar `.//build/sunflower-0.3-60.tar` from there.
Obviously, this problem had place for `dist-rpm` target as well.
Changed target branch to `release`, original pull request #165.
=> Makefile: Untar archive to specified destination

application/gui/main_window.py
This bug occurs on all new installations.
Steps to reprodyce:
1. delele window config ~/.config/sunflower/windows.json
2. run sunflower
3. change directory or calculate dir size
when spinner wil be shown active panel will change its size and change back when the spinner will disappear
=> Fix bug with resizing panel size when showing spinner.

application/gui/main_window.py, application/widgets/title_bar.py
1) Fixes issue with command entry widget - apparently insert_text() needs an additional parameter now - tested by entering e.g. 'cd /home/username'
2) Fix for initialized variable error from Python further down when hitting line with "self._spinner_counter += 1"
=> Fix for GTK3 issues

application/gui/about_window.py
without translator being defined there will be an error further down...
=> Fix missing translators in about_window.py

application/gui/input_dialog.py, application/mounts.py, application/operation.py
This should fix issues
#194 The crash during deleting a hidden folder .Trash-* from an external flash drive in Ubuntu 15.10
#197 A crash during deleting a folder without permissions
I removed QuestionOperationError. There were no sub classes and after wrapping (or removing) the unused Gtk.ResponseType.NO/YES code there was nothing left to keep.
The change to mounts.py fixes an error with mounted flash drives not being processed correctly on Sunflower startup.
=> Fix handling of file deletion error/retry

application/associations.py
Fixing issue 195 - launching files with # % etc in file name.
This is using urllib to do the URI encoding but only if applicable ie. file gets launched with file:// URL.
=> Fixing issue 195 - launching files with # % etc in file name

application/plugins/file_list/file_list.py
… which doesn't seem to be defined in at least Gtk 3.10.8 (Ubuntu 14.04.4 LTS)
=> Fix missing Gtk.TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID 

application/gui/preferences/associations.py, application/gui/preferences/item_list.py, application/plugins/file_list/file_list.py, application/plugins/rename_extensions/default.py
I searched for get_position() calls and reviewed them. All affected lines in PR triggered a traceback on console before and went silent afterwards. 
Images are now displayed in fast media preview.
=> Fix for issues #229 - Fast media preview not working - changed window to get_window()

application/main.py, application/plugin_base/terminal.py, application/plugins/system_terminal/plugin.py
Fix for issues #177 - After GTK3 switch - Sunflower doesn't start on Debian Jessie due to missing GConf
I have made usage of GConf optional. It was used to get system font for Vte terminal. Vte terminal is working now too.
=> Fix for Debian Jessie without GConf

application/gui/main_window.py
This fixes issue #182 - this seemed the only reliable way to close Sunflower from the menu. The change behaviour appears to be a consequence of the changed way the application is launched in the first place (combination of Gtk.Application and Gtk.ApplicationWindow in main.py)
Pressing Alt-F4 or clicking the windows [X] close icon is unaffected.
=> Fix Quit menu item

sunflower/plugins/archive_support/zip_provider.py
Basic fix for #336 . If timestamp generation errors out - set default timestamp value.
Not sure if setting timestamp to 0 is best idea, as different archive and file managers solves this issue in different ways:
mc - shows date 1979 12 31 00:00
FileRoller - shows date 1979 11 30 00:00
Total Commander (on windows) - does not display date for such files
unzip - shows date as 1980 00 00 00:00
=> Archive support: fix issue with invalid timestamps

sunflower/tools/version_check.py
Fixes issue #334 .
Tested on Fedora 30 with Python 3.7.3
=> Version check: decode response before parsing data

sunflower/gui/input_dialog.py, sunflower/plugins/file_list/trash_list.py
Update incorrect icon names: "Empty trash" in Trash can tab and operation queue select in delete dialog.
=> Updated incorrect icon names

sunflower/tools/viewer.py
Fix for viewer plugin to allow opening 0 bytes text files without errors.
=> Viewer plugin: fix error opening empty text file

sunflower/plugins/default_toolbar/bookmark_button.py, sunflower/plugins/default_toolbar/bookmarks_button.py, sunflower/plugins/default_toolbar/home_directory_button.py, sunflower/plugins/default_toolbar/parent_directory_button.py, sunflower/plugins/default_toolbar/separator.py
Fixes #326 . While toolbar now functions without errors, fix revealed few more issues: item ordering does not work, problems with bookmarks menu popup. I'll open separate issues for those.
=> Plugins: Default Toolbar: add missing imports

sunflower/gui/main_window.py
Copy path to clipboard works correctly now. Fixes #318
=> Fixed copy path to clipboard error

sunflower/plugins/file_list/file_list.py
Pressing F4 (or clicking view button) on directory and "go up" item was showing error in console. I've added error dialog similar to one in mc and Total Commander, to inform user that for edit command they have to select a file.
=> Prevent errors when edit command is executed on directories

sunflower/icons.py
Updated desktop icon to match other user directories icons style.
Before:
After:
=> Icon manager: updated desktop icon

sunflower/mounts.py
Fixes #360 . I'm pretty sure that Python handles variable unreferencing (https://mail.gnome.org/archives/python-hackers-list/2013-February/msg00002.html).
=> Mounts manager: Fixed mount open error

sunflower/plugins/file_list/file_list.py
```
sunflower/plugins/file_list/file_list.py:2060: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
=> fix SyntaxWarning

sunflower/plugin_base/item_list.py
Keep 'selected' status on matched item after search panel closed.
It should has been selected, but unselected after search panel closed.
It seems that the text in search panel is selected before panel closed, which cause the item lost 'selected' status.
If nothing was selected, nothing will be selected.
=> select matched item after search closed

sunflower/plugins/file_list/file_list.py
If nothing matched by quick search, nothing will selected.
It cause such a exception if try to open context menu by keybinding:
```
Traceback (most recent call last):
File "/var/build/sunflower3/sunflower/accelerator_group.py", line 93, in _handle_activate
result = callback_method(widget, label)
File "/var/build/sunflower3/sunflower/plugin_base/item_list.py", line 1221, in _show_open_with_menu
self._prepare_popup_menu()
File "/var/build/sunflower3/sunflower/plugins/file_list/file_list.py", line 1147, in _prepare_popup_menu
is_dir = item_list.get_value(selected_iter, Column.IS_DIR)
TypeError: Argument 1 does not allow None as a value
```
This PR try to fix this exception by setting the target of context menu to the 'cursor' item instead.
=> correctly show context menu if nothing selected

sunflower/plugin_base/item_list.py
If nothing selected (e.g. search panel closed with nothing matched), move_marker keybinding does nothing.
This PR let the marker move from the 'cursor' item if nothing selected, make keybinding does work.
This PR also change the way of getting the next/previous item to using gtk defined function `iter_next` and `iter_previous`, instead of 'path +/- 1'.
=> move marker if nothing selected

sunflower/gui/preferences_window.py, sunflower/plugin_base/item_list.py
This PR stop keybinding handling after showing openwith menu and preference window, so command extry will not open togther with them.
=> skip command entry after openwith menu and preference window keybinding

sunflower/gui/main_window.py
This PR set the tab label scrollable, so that the width of panel will not changed when diving into a directory with a very long name.
=> set tab label scrollable

sunflower/__main__.py, sunflower/gui/preferences/display.py, sunflower/keyring.py, sunflower/notifications.py
This PR does several things:
1. start without gir-notify will not failed.
2. only initialize widget in keyring if  gir-gnomekeyring is available.
3. grayout checkbox of notifications option if gir-notify is not available.
=> fix gi import in keyring and notifications

sunflower/gui/main_window.py
`MainWindow._vbox2` is never defined, so exception raised when change the horizontal split preference.
This PR fix it by getting the box parent of `MainWindow._paned`.
=> fix exception when setting horizontal split

sunflower/widgets/tab_label.py
The `Label.set_max_width_chars` of tab lab does not work as expected neither with nor without `Pango.EllipsizeMode`.
Without `Pango.EllipsizeMode`, the whole text of label is showed no matter the max chars.
With `Pango.EllipsizeMode`, the text is ellipsized to only two chars. It is too short.
This PR try to fix this issue.
If the text is too long, which is longer than `TabLabel.MAX_CHARS`, set the width of label to `TabLabel.MAX_CHARS` and set it ellipsized.
If the text is not too long, which is shorter than `TabLabel.MAX_CHARS`, set the width of label to auto fit the text and not ellipsized.
The `TabLabel.MAX_CHARS` is set to 20, which is already defined, but may better to be a option.
=> ellipsize tab label if over max chars

sunflower/operation.py
If silent merge is enabled, no dialog would be shown to user and no result, so this exception raised.
This PR fix this issue by return the merge value earlier so the result will not be referenced.
BTY, why not following PEP-8 but using tab for indentation?
=> fix UnboundLocalError in silent merge

sunflower/plugin_base/item_list.py, sunflower/plugins/file_list/file_list.py, sunflower/plugins/file_list/local_monitor.py
My long overdue attempt to fix trash list file monitor, should fix #328 .
Had to disable provider caching, as it causes problems with trash list. Removed parent directory skipping, as some special directories like trash doesn't have row "go up". Removed manual cursor moving after removing item, as in GTK3 it sorts itself out. Finally, when creating new monitor for trash folder we need to use new_for_uri() function.
=> Fix issue with trash list file monitor

sunflower/gui/main_window.py
Fix initial window size parameters, now on first start window will have correct size. Fixes #316 .
Also changed handle_position quotes, as they were different from the rest.
=> Fix setting initial window geometry

sunflower/gui/main_window.py, sunflower/gui/preferences/toolbar.py, sunflower/toolbar.py
Moved toolbar items to array to solve ordering issue #352 , removed two redundant icon sizes #395 . Added feature to rename toolbar buttons from list. Fixed formatting where spaces were used.
I don't like my current workaround for toolbar plugin extra data (storing json in listview), and applying active toolbar styles that requires to keep duplicate options array (similar implementation is used in item_list options). Would be great to hear suggestions how to implement them better.
At least now toolbar base is working and we can add a few more button plugins to make it perfect.
=> Toolbar fixes

sunflower/operation.py, sunflower/plugin_base/provider.py, sunflower/plugins/file_list/local_provider.py
This PR use `(st_atime_ns, st_mtime_ns)` instead of `(st_atime, st_mtime)` in `os.utime` to set timestamp exactly.
Below is a sample code to show the difference (pay attention to every atime_ns and mtime_ns):
```python3
import os
import time
fmt='atime: {}, atime_ns: {}, mtime: {}, mtime_ns: {}'
with open('a',mode='wb'):pass
a_stat=os.stat('a')
print('timestamp of a')
print(fmt.format(a_stat.st_atime,a_stat.st_atime_ns,a_stat.st_mtime,a_stat.st_mtime_ns))
time.sleep(1)
with open('b',mode='wb'):pass
print('timestamp of b, set with st_atime/st_mtime')
os.utime('b',times=(a_stat.st_atime,a_stat.st_mtime))
b_stat=os.stat('b')
print(fmt.format(b_stat.st_atime,b_stat.st_atime_ns,b_stat.st_mtime,b_stat.st_mtime_ns))
print('timestamp of b, set with st_atime_ns/st_mtime_ns') …
```
=> use nanoseconds in os.utime

sunflower/plugin_base/toolbar_factory.py, sunflower/plugins/default_toolbar/bookmark_button.py, sunflower/plugins/default_toolbar/plugin.py, sunflower/toolbar.py
Fixed parent window references for modal dialogs in Toolbar preferences. Updated "Bookmark Button" edit dialog style to use header bar and removed name editing field, as it was not very useful in disabled state.
Fixes #398
=> Toolbar fix bookmark button edit warning

sunflower/plugin_base/terminal.py
While triaging issue #234 found a bit different issue and fixed it. This probably closes #234 too, as functionality mentioned in issue is working correctly.
=> Terminal: fix argument passed to feed_child function

sunflower/plugin_base/item_list.py
As requested in #127 when selection is over directory, highlighted directory is opened in opposite panel. When selected file or parent directory item - current path is opened. Works with terminal too.
Fixes #127 
Nice improvement might be to use single function for _inherit_left_path() and _inherit_right_path(), but I currently have no idea how to implement that correctly.
=> Item list: improve inherit path functionality

sunflower/plugin_base/item_list.py, sunflower/plugins/file_list/file_list.py
My last attempt to fix trash list https://github.com/MeanEYE/Sunflower/commit/e18476119a985042138d3b05acbfaec6a7ece96d resulted in broken archive support.
This commit with upcoming one, that fixes bug in breadcrumbs, should result in correctly working zip archive provider and trash list.
get_provider() function checking hidden files used incorrect path and that resulted in provider being switched to localProvider.
=> File list: fix issue with incorrectly set providers

sunflower/widgets/breadcrumbs.py
After opening zip archive, breadcrumbs button with current path is activated. That causes first button to get clicked event first and do a path change to parent directory. Combined with provider change that resulted in empty archive listing. Opening zip archive second time works correctly, because breadcrumbs bar is already set to correct location.
When testing current version after opening zip archive one will notice that it has incorrect "folder" icon set and error in terminal complaining about not being able to open directory.
=> Breadcrumbs: fix unnecessary path change

sunflower/operation.py
StandardError class was removed from Pyhton3, replaced with Exception. Now errors during file operations are displayed in dialogs, not in terminal output.
=> Replace StandardError with Exception

sunflower/plugins/archive_support/zip_provider.py, sunflower/plugins/file_list/gio_provider.py
This PR try to fix #408.
I could not exactly point where the exception raised, but any `FileInfoExtended` should inited with *_ns attribute.
=> set time_*_ns in any FileInfoExtended

sunflower/gui/main_window.py
Move cursor over directory or parent directory indicator in file list. Press "Edit" button in command bar. Error modal dialog is opened without parent, so it doesn't dim main window correctly.
Added parent param to fix that issue.
=> Main window: pass self reference to edit dialog

sunflower/plugins/archive_support/zip_provider.py
Simple workaround for breadcrumbs issue when opening zip archive. Just copied functionality from local_provider.py When different mount display (remote drives, optical drives, etc.) will be implemented in breadcrumbs, this will need adjusting. Until then having this fix will help to find other existing issues with breadcrumbs and zip provider.
Fixes #332
=> Archive support: return correct root path

sunflower/mounts.py
Sunflower attempt to mount volumes even volume already mounted which entails the errors
```
Traceback (most recent call last):
File "/home/arseniy/Sunflower/sunflower/mounts.py", line 45, in _handle_mount_finish
mount.mount_finish(result)
gi.repository.GLib.Error: g-io-error-quark: mount: /: must be superuser to use mount.
(0)
Traceback (most recent call last):
File "/home/arseniy/Sunflower/sunflower/mounts.py", line 45, in _handle_mount_finish
mount.mount_finish(result)
gi.repository.GLib.Error: g-io-error-quark: mount: /boot: must be superuser to use mount.
(0)
```
To avoid this we should check is volume already mounted https://developer.gnome.org/pygobject/stable/class-giovolume.html#method-giovolume--get-mount
=> MountsManager: check volume is mounted before mount

setup.py, sunflower/common.py, sunflower/gui/main_window.py, sunflower/icons.py, sunflower/indicator.py, sunflower/notifications.py
Please consider those changes to make Sunflower working when installed as legit Python package, After merge I'd appreciate if you could do (beta) release of it, so we can finally drop Python2-only Sunflower from Gentoo.
Ideally you could switch to python-stdeb to build legit .deb with sunflower, while passing some additional options to add non-python dependencies there. That would allow to simplify code and always rely on sys.prefix.
=> Setup.py fixes

sunflower/gui/keyring_manager_window.py, sunflower/plugins/file_list/gio_provider.py
The former was removed in Python 3, int is now unbounded.
This fixes error:
Traceback (most recent call last):
File "/nix/store/0pgpnirdcai1ggv4a6xn6i9aw72zz2vx-sunflower-2020-07-03-unstable/lib/python3.8/site-packages/sunflower/gui/main_window.py", line 2507, in show_keyring_manager
KeyringManagerWindow(self)
File "/nix/store/0pgpnirdcai1ggv4a6xn6i9aw72zz2vx-sunflower-2020-07-03-unstable/lib/python3.8/site-packages/sunflower/gui/keyring_manager_window.py", line 46, in __init__
self._store = Gtk.ListStore(long, str, str)
NameError: name 'long' is not defined
=> Replace long with int

MANIFEST.in, sunflower/gui/main_window.py
setup.py does not install .conf files by default, leading to descriptions not being shown.
=> Install plug-in .conf files

sunflower/icons.py
Use correct icon name for Downloads folder, now files list and properties window will display correct icon, same as GNOME Files.
=> Icons: use correct icon name for Downloads folder

sunflower/operation.py
This PR fix UnboundLocalError caused by wrong indent in `Operation._get_overwrite_input`.
=> fix UnboundLocalError in overwrite_input

sunflower/plugin_base/item_list.py, sunflower/plugins/file_list/file_list.py
Updated deprecated menu popup() functions in item_list and file_list. Fixes #434 . Popups in items list are correctly positioned and doesn't go outside of screen. Tested on Wayland, also tested with "Menu" keyboard key to make sure that menu popups does not cover selected item.
I've left single popup() function not updated, because I couldn't find a way to call that function, more info #462 .
=> Item list: updated deprecated menu popup functions

sunflower/gui/preferences/associations.py, sunflower/gui/preferences/item_list.py, sunflower/plugin_base/terminal.py, sunflower/plugins/rename_extensions/default.py, sunflower/widgets/tab_label.py
Updated deprecated menu.popup() functions. This results in simplified code, as we don't need so much calculations any more - all work is done by popup_at_widget() function. Also there should be no more issues with menus going off screen, at least in Wayland.
There is still one popup() function left not updated in indicator.py file, as it is using deprecated Gtk.StatusIcon(). I've created separate issue #467 for that discussion.
=> Updated deprecated menu popup functions

sunflower/gui/about_window.py, sunflower/gui/error_list.py, sunflower/gui/history_list.py, sunflower/gui/input_dialog.py, sunflower/gui/keyring_manager_window.py, sunflower/gui/main_window.py, sunflower/gui/preferences_window.py, sunflower/plugins/file_list/dialogs.py, sunflower/tools/advanced_rename.py, sunflower/tools/find_files.py, sunflower/tools/version_check.py, sunflower/tools/viewer.py
Removing deprecated set_wmclass functions as [recommended in GTK docs](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Window.html#Gtk.Window.set_wmclass):
> Don’t use this function. It sets the X Window System “class” and “name” hints for a window. According to the ICCCM, you should always set these to the same value for all windows in an application, and GTK+ sets them to that value by default, so calling this function is sort of pointless.
=> Remove deprecated set_wmclass functions

sunflower/icons.py
Use correct icon names for default file and folder, remove fallbacks to deprecated Gtk.STOCK icons. 
Left side - before fix (notice missing image icons), right side - after fix:
Also fixed home icon name, so it is correctly displayed in file list and properties.
Fixes #455
=> Icons: update deprecated icons names

sunflower/gui/main_window.py
Fixes #456 , also fixes "index out of range" issue when clipboard is empty and Ctrl+V hotkey is pressed.
=> Main window: fix clipboard selection check

sunflower/plugins/file_list/file_list.py
Pressing Ctrl+E on any row in items list shows emblem menu. Currently only text labels are displayed (at least on my Fedora OS). This commit forces emblem icons always to be displayed.
=> File List: always show emblem icons in emblem menu

sunflower/plugins/file_list/gio_provider.py
Previously "empty icon" were displayed for samba, FTP and other network providers. This commit fixes the issue.
Icons for other providers are displayed correctly.
=> File list: update context menu icons for network providers

sunflower/gui/main_window.py, sunflower/plugins/rename_extensions/audio_metadata.py, sunflower/tools/advanced_rename.py
Few minor improvements for Advanced rename plugin. Not opening plugin window with no items selected should prevent some bug reports in the future.
=> Advanced rename fixes

sunflower/plugins/archive_support/zip_provider.py
Prevent unpacking files with permissions set to 0, where user will need to use sudo to remove or access them. Issue observed with "fat" type files in zip. Also fixes issue when unzip errors out after unpacking first directory and cannot write files inside due to permissions.
Default file and directory permission values where taken from Gnome Archive Manager.
Fixes #302 
I know, that this is not perfect solution, but at least it makes Sunflower inbuilt zip unpacker much more useful, for now. In the future I suppose unpacker might switch to libarchive (if user has it installed) to provide much better unpacking features support.
=> Zip provider: set default permissions

sunflower/gui/main_window.py, sunflower/gui/shortcuts_window.py
Display keyboard shortcuts using Gtk.ShortcutsWindow widget. Uses accelerator_manager to get accelerator keys, so the list is always up to date. ShortcutsWindow provides search functionality.
Fixes #196
=> Add Keyboard Shortcuts window

sunflower/gui/input_dialog.py
In create file dialog template "Empty file" had "unknown image" icon. This commit sets correct icon name.
=> Fix icon for empty file template

sunflower/gui/input_dialog.py
OK button was missing on PathInputDialog, this commit fixes that.
Found same issue with Add Bookmark dialog, added commit for it too.
=> Input dialog: add missing OK button to PathInputDialog

sunflower/plugins/file_list/file_list.py
Since https://github.com/MeanEYE/Sunflower/commit/43d93a9beac236d5a6c43bfb1de0b62b697b0a8f, individual sorting method  is used instead of 'Gtk.TreeSortable.set_sort_func'. It means that pygi/gtk does not manage the scrolling after sorting, so that the selected item may scrolled out of the 'view part' (e.g. large numbers of items add and sorted before the selected item).
This PR try to fix this problem by doing scroll after each sorting operation.
=> always scroll to selection after file list sorted

sunflower/gui/main_window.py
Thank you for building and maintaining this excellent tool.
On my Ubuntu 20.04 system, Sunflower always starts with the right pane focused. It seems like `new_tab.focus_main_object()` (which happens for the right pane last) somehow overrides the later `notebook.grab_focus()`. I don’t really understand why this happens. But this PR fixes the problem for me.
=> Main window: Fix initial notebook focus.

sunflower/__main__.py
It wasn’t obvious to me that I could pass arguments to those options until I saw it in the source code.
=> Fix help for command-line arguments

sunflower/plugin_base/item_list.py, sunflower/plugins/file_list/file_list.py
Fixes #502, as well as another similar instance I spotted. However, I didn’t attempt to find all instances of this or similar bugs.
=> File list: Fix Gtk.MessageDialog transient_for.

sunflower/associations.py, sunflower/gui/main_window.py, sunflower/gui/preferences/item_list.py
I have many executable shell and Python scripts. When I activate them in a file manager, I always want to open them as text files, never to execute them. I like how GNOME Files handles this: it has an option to always execute, always open, or ask every time. This commit adds a similar option to Sunflower, except that “ask every time” is not yet implemented (because I don’t need it) — but it should be easy to add later.
=> File list: Make executing files optional.
