application/plugins/find_file_extensions/default.py

'Case insensitive file name search'

Find file extensions: Default: Fix MeanEYE/Sunflower#70

---

application/plugins/file_list/file_list.py

We already have scheme in selection exept local provider.

File List: Fix dnd output path

---

application/plugins/file_list/file_list.py

File list: Add auto-scroll when gragged item is near the margin. Close MeanEYE/Sunflower#81

---

application/gui/preferences/accelerators.py

Backspace disable current accelerator, if accelerator already disabled then assign backspace

Fix MeanEYE/Sunflower#109

---

.gitignore
application/tools/viewer.py

Make viewer try to detect character encoding of file in order to better handle none ASCII/UTF-8 cases.

Make viewer try to detect character encoding of file

---

application/gui/main_window.py

There're Alt- shortcuts for some things in the menu but not others.

Alt menu keys

---

application/gui/main_window.py
application/gui/preferences/display.py
application/widgets/completion_entry.py

Sorry, messed up my branch previously.

Use network path completion checkbox.

---

application/mounts.py
application/plugins/file_list/gio_provider.py
application/plugins/file_list/plugin.py

Add MTP and Gphoto2 GIO provider to handle e.g. Android phones connecting on an USB cable

Add MTP and Gphoto2 GIO provider to handle e.g. Android phones connecting

---

application/accelerator_manager.py
application/gui/preferences/accelerators.py

Preferences: Accelerators: check collisions on changed accelerators.

---

application/plugins/owner_column/plugin.py

Owner column: Fix import "Column" from file_list

---

application/gui/input_dialog.py
application/operation.py
application/plugins/file_list/file_list.py
application/plugins/file_list/local_provider.py
application/tools/version_check.py
application/widgets/emblems_renderer.py

Dialogs still looks ugly, but they works.

Some fixes in dialogs.

---

application/plugins/file_list/file_list.py

Fix for #198

---

application/gui/input_dialog.py
application/tools/viewer.py
application/widgets/thumbnail_view.py

Add import for GdkPixbuf and remove call to set_margin_start() (added in GTK 3.12)

Add import for GdkPixbuf and remove call to set_margin_start()

---

application/gui/mounts_manager_window.py
application/gui/properties_window.py
application/mounts.py
application/plugins/file_list/file_list.py
application/plugins/file_list/gio_extension.py
application/plugins/file_list/gio_provider.py
application/plugins/file_list/gio_wrapper.py
application/widgets/bookmarks_menu.py

Replacing PR #191 with a tiny modification.

Reworking changes around Mount Manager and GIO Extension

---

application/operation.py

Fixed up for file rename - change to import and global replace of GObject with GLib

Fix up ops for GTK3

---

application/associations.py
application/tools/viewer.py

Fix issue around escaping double-quote while launching external application, fix for incorrect GTK3 key constants

Fix issue around escaping double-quote while launching external app

---

application/keyring.py
application/plugins/file_list/gio_extension.py

This restores keyring functionality from before the GTK3 switch

Fix for issues #172 - Still importing GTK2 libraries - gnomekeyring

---

application/gui/input_dialog.py

This fixes errors in GTK 3.10 due to missing header bar support.

Fix for issues #219 - header bars should be optional

---

application/main.py

I think this is the best solution for us to fix issue 217 - see my comments there.

Issues 217 - Fix for handling file names with non ASCII characers

---

application/gui/preferences/associations.py
application/gui/preferences/item_list.py
application/plugin_base/item_list.py
application/plugin_base/terminal.py
application/plugins/rename_extensions/default.py
application/widgets/bookmarks_menu.py
application/widgets/title_bar.py

menu.popup() callback signature was changes from func(menu, user_data) to func(menu, x, y, user_data)

Fix popups.

---

application/gui/input_dialog.py

This removes code trying to make header bars optional.

Remove code trying to make header bars optional

---

sunflower/tools/viewer.py

Added early check to viewer plugin if provided path is a directory.  Fixes #333

Do not open directories with viewer

---

sunflower/plugin_base/item_list.py

File list: Automatically hide vertical scrollbar

---

sunflower/tools/disk_usage.py

Disk usage: fix opening directory after size calculation

---

sunflower/__main__.py

This PR set Sunflower.application_id to None for multiple instances.

set Sunflower.application_id

---

sunflower/plugins/find_file_extensions/contents.py

Fixed file search by contents functionality by encoding string before comparing.
Also fixed misspelled comment.

Fixed file search by contents

---

sunflower/gui/preferences_window.py

Preferences window: fix help link

---

.pylintrc

Let's add linting rules to improve source code quality and catch errors early. This is a biased rules config, I tried adjusting it to Coding Style rules from Sunflower Wiki. Please review it as some rules still might need adjusting.

Add pylint rules

---

sunflower/plugin_base/item_list.py

Removed all unused functions related to history menu from items list. Fixes #462 .

Item list: Remove unused history menu functions

---

sunflower/plugin_base/find_extension.py
sunflower/tools/find_files.py

Fixes #418
Also removed debug print statement and made window into modal.

Find Files: fix search functionality

---

sunflower/common.py

Not really sure about this solution, used a template variable for better readability, as single character change quickly got lost in longer lines. Fixes #146

Hide decimal places for byte sized values

---

sunflower/widgets/completion_entry.py

Sorting in path completion was not working. Fixes #452

Completion entry: sort fix

---

sunflower/gui/preferences/item_list.py

Fix add directory menu button, broken in #468 update

Preferences: fix add directory menu

---

sunflower/gui/about_window.py
sunflower/gui/error_list.py
sunflower/gui/history_list.py
sunflower/gui/input_dialog.py
sunflower/gui/keyring_manager_window.py
sunflower/gui/main_window.py
sunflower/gui/preferences_window.py
sunflower/plugins/file_list/dialogs.py
sunflower/tools/advanced_rename.py
sunflower/tools/find_files.py
sunflower/tools/version_check.py
sunflower/tools/viewer.py

Revert "Remove deprecated set_wmclass functions"

---

sunflower/plugins/file_list/file_list.py

Fixes #500.
There was a confusion between paths relative to `self.path` (the top level of the `FileList`) and to the parent (the expanded tree node). The former was passed to `_delete_item_by_name`, but `_find_iter_by_name` expected the latter. I changed it all to the latter, adding an extra `parent_path` parameter where necessary, as was already the case with `_update_emblems_by_name`, etc.
This is all brittle, there are other path-related bugs around, so working with paths should probably be refactored somehow, but so far I cannot propose or implement such a refactoring.
Along the way, I noticed and removed two unused pieces of code. `if other_path is None` was never taken because `other_path` was already being used above; and if it were somehow taken, it would mistakenly skip the …

File list: Fix updating upon monitor events.
